apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: {{ .Values.orderService.replicaCount }}
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: "{{ .Values.orderService.image.repository }}:{{ .Values.orderService.image.tag }}"
          ports:
            - containerPort: 8080
          resources:
            {{- toYaml .Values.orderService.resources | nindent 12 }}
      nodeSelector:
        {{- toYaml .Values.orderService.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.orderService.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.orderService.affinity | nindent 8 }}
