apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  type: {{ .Values.orderService.service.type }}
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: order-service
