apiVersion: v2
name: order-service
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
type: application

# The version of the chart
version: 0.1.0

# The version of the application that this chart installs
appVersion: "1.0"
