apiVersion: v1
kind: Service
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  type: {{ .Values.product-service.service.type }}
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: product-service
