apiVersion: v1
kind: Service
metadata:
  name: {{ include "aitdevops-site.fullname" . }}
  labels:
    {{- include "aitdevops-site.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    {{- include "aitdevops-site.selectorLabels" . | nindent 4 }}
