apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: {{ .Values.user-service.replicaCount }}
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: "{{ .Values.user-service.image.repository }}:{{ .Values.user-service.image.tag }}"
          ports:
            - containerPort: 80
          resources:
            {{- toYaml .Values.user-service.resources | nindent 12 }}
      nodeSelector:
        {{- toYaml .Values.user-service.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.user-service.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.user-service.affinity | nindent 8 }}
