apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  type: {{ .Values.user-service.service.type }}
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: user-service
