name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      CLUSTER_ZONE: ${{ secrets.CLUSTER_ZONE }}
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      ARTIFACT_REPO: aitdevops

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        service_account_key: ${{ secrets.GOOGLE_CREDENTIALS }}
        export_default_credentials: true

    - name: Configure Docker for GCP Artifact Registry
      run: gcloud auth configure-docker

    - name: Build and push frontend Docker image
      run: |
        cd frontend
        docker build -t $ARTIFACT_REPO/frontend:latest .
        docker tag $ARTIFACT_REPO/frontend:latest $REGION-docker.pkg.dev/$PROJECT_ID/$ARTIFACT_REPO/frontend:latest
        docker push $REGION-docker.pkg.dev/$PROJECT_ID/$ARTIFACT_REPO/frontend:latest

    - name: Build and push product-service Docker image
      run: |
        cd services/product-service
        docker build -t $ARTIFACT_REPO/product-service:latest .
        docker tag $ARTIFACT_REPO/product-service:latest $REGION-docker.pkg.dev/$PROJECT_ID/$ARTIFACT_REPO/product-service:latest
        docker push $REGION-docker.pkg.dev/$PROJECT_ID/$ARTIFACT_REPO/product-service:latest

    - name: Build and push order-service Docker image
      run: |
        cd services/order-service
        docker build -t $ARTIFACT_REPO/order-service:latest .
        docker tag $ARTIFACT_REPO/order-service:latest $REGION-docker.pkg.dev/$PROJECT_ID/$ARTIFACT_REPO/order-service:latest
        docker push $REGION-docker.pkg.dev/$PROJECT_ID/$ARTIFACT_REPO/order-service:latest

    - name: Build and push user-service Docker image
      run: |
        cd services/user-service
        docker build -t $ARTIFACT_REPO/user-service:latest .
        docker tag $ARTIFACT_REPO/user-service:latest $REGION-docker.pkg.dev/$PROJECT_ID/$ARTIFACT_REPO/user-service:latest
        docker push $REGION-docker.pkg.dev/$PROJECT_ID/$ARTIFACT_REPO/user-service:latest

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials $CLUSTER_NAME --zone $CLUSTER_ZONE --project $PROJECT_ID

    - name: Deploy to GKE using Helm
      run: |
        helm upgrade --install frontend ./helm/frontend --set image.repository=$REGION-docker.pkg.dev/$PROJECT_ID/$ARTIFACT_REPO/frontend
        helm upgrade --install product-service ./helm/product-service --set image.repository=$REGION-docker.pkg.dev/$PROJECT_ID/$ARTIFACT_REPO/product-service
        helm upgrade --install order-service ./helm/order-service --set image.repository=$REGION-docker.pkg.dev/$PROJECT_ID/$ARTIFACT_REPO/order-service
        helm upgrade --install user-service ./helm/user-service --set image.repository=$REGION-docker.pkg.dev/$PROJECT_ID/$ARTIFACT_REPO/user-service
