name: Update Helm Values and Push Changes

on:
  push:
    branches:
      - main

jobs:
  update-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure git
        run: |
          git config --global user.email "rajeevkoppisetti21@gmail.com"
          git config --global user.name "aitdevops"

      - name: Clone argocd repo
        run: |
          git clone https://${{ secrets.GH_TOKEN }}@github.com/aitdevops/argocd.git
          cd argocd
          git checkout main

      - name: List files in the repository
        run: |
          cd argocd
          ls -R

      - name: Update Helm values
        run: |
          cd argocd
          sed -i 's|tag:.*|tag: '${{ github.sha }}'|g' charts/aitdevops-site/values.yaml
          git add charts/aitdevops-site/values.yaml
          git commit -m "Update frontend image to ${{ github.sha }}"

      - name: Push changes
        run: |
          cd argocd
          git push https://${{ secrets.GH_TOKEN }}@github.com/aitdevops/argocd.git main
