name: Manual Rollback

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Helm release name'
        required: true
      revision:
        description: 'Revision number to rollback to'
        required: true

jobs:
  rollback:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.PROJECT_ID }}
        install_components: kubectl

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: 'v3.5.2'

    - name: Rollback Helm Release
      run: |
        gcloud container clusters get-credentials ${{ secrets.CLUSTER_NAME }} --zone ${{ secrets.CLUSTER_ZONE }} --project ${{ secrets.PROJECT_ID }}
        helm rollback ${{ github.event.inputs.release }} ${{ github.event.inputs.revision }}

